server:
  port: 8070
eureka:
  instance:
    hostname: localhost
  client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://127.0.0.1:8070/eureka/

  server:
    waitTimeInMsWhenSyncEmpty: 5