server:
  port: 8069
eureka:
  instance:
    preferIpAddress: true
  client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://127.0.0.1:8070/eureka/
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true